version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
      - nginx_logs:/var/log/nginx  # NEW: Mount shared volume
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network
    

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    ports:
      - "8081:3000"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT:-3000}
    networks:
      - app_network

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    ports:
      - "8082:3000"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT:-3000}
    networks:
      - app_network

  alert_watcher:
    image: python:3.11-slim
    container_name: alert_watcher
    volumes:
      - ./watcher.py:/app/watcher.py
      - ./requirements.txt:/app/requirements.txt
      - nginx_logs:/var/log/nginx
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD}
      - WINDOW_SIZE=${WINDOW_SIZE}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC}
    working_dir: /app
    command: >
      sh -c "pip install --quiet -r requirements.txt && python -u watcher.py"
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

# NEW: Shared volume for logs
volumes:
  nginx_logs: